spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/pi_banho_e_tosa}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
server:
  port: ${PORT:8080}
  servlet:
    context-path: /api
app:
  jwt:
    secret: ${JWT_SECRET:change-me-please-change-me-please}
    expiration: ${JWT_EXPIRATION:PT4H}
  schedule:
    start-hour: 9
    end-hour: 18
    slot-minutes: 30
